name       : s-tui
version    : 1.1.3
release    : 2
source     :
    - https://github.com/amanusk/s-tui/archive/refs/tags/v1.1.3.tar.gz : 1281b3560f6e2de29f26f7b014c7a1b35121718d96de27e5fe75f6eddc12a762
license    : GPL-2.0-or-later
component  : system.utils
summary    : Terminal-based CPU stress and monitoring utility
description: |
    Stress-Terminal UI, s-tui, monitors CPU temperature, frequency, power and utilization in a graphical way from the terminal.
rundeps    :
    - python-psutil
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
