name       : s-tui
version    : 1.1.4
release    : 3
source     :
    - https://github.com/amanusk/s-tui/archive/refs/tags/v1.1.4.tar.gz : aeebcf7b04beb8526c98d675ae2b2f106fd1e00343b0c37c78b4a84c31561d0b
license    : GPL-2.0-or-later
component  : system.utils
summary    : Terminal-based CPU stress and monitoring utility
description: |
    Stress-Terminal UI, s-tui, monitors CPU temperature, frequency, power and utilization in a graphical way from the terminal.
rundeps    :
    - python-psutil
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
